[project]
name = "computer-vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.3.3",
    "opencv-contrib-python>=4.11.0.86",
    "pandas>=2.3.2",
    "scipy>=1.16.1",
]
